//! Embeds weapon PNG/SVG and game logos as `data:` URLs at compile time (no WebView asset fetch).

use base64::{engine::general_purpose::STANDARD, Engine};
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest_dir).join("..");
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("embedded_weapon_icons.rs");

    let weapons: &[(&str, &str, &str)] = &[
        ("pubg", "m416", "assets/weapons/pubg/m416.png"),
        ("pubg", "akm", "assets/weapons/pubg/akm.png"),
        ("pubg", "scarl", "assets/weapons/pubg/scarl.png"),
        ("pubg", "beryl", "assets/weapons/pubg/beryl.png"),
        ("pubg", "vector", "assets/weapons/pubg/vector.png"),
        ("pubg", "mini14", "assets/weapons/pubg/mini14.png"),
        ("rust", "ak47", "assets/weapons/rust/ak47.png"),
        ("rust", "lr300", "assets/weapons/rust/lr300.png"),
        ("rust", "mp5a4", "assets/weapons/rust/mp5a4.png"),
        ("rust", "thompson", "assets/weapons/rust/thompson.png"),
        ("rust", "custom", "assets/weapons/rust/custom.png"),
        ("rust", "m249", "assets/weapons/rust/m249.png"),
        ("cs2", "ak47cs", "assets/weapons/cs2/ak47cs.svg"),
        ("cs2", "m4a4", "assets/weapons/cs2/m4a4.svg"),
        ("cs2", "m4a1s", "assets/weapons/cs2/m4a1s.svg"),
        ("cs2", "famas", "assets/weapons/cs2/famas.svg"),
        ("cs2", "galil", "assets/weapons/cs2/galil.svg"),
        ("cs2", "mp9", "assets/weapons/cs2/mp9.svg"),
    ];

    let logos: &[(&str, &str)] = &[
        ("pubg", "assets/pubg.svg"),
        ("rust", "assets/rust.svg"),
        ("cs2", "assets/cs2.svg"),
    ];

    let mut code = String::from(
        "// @generated by build.rs — weapon / game images as data: URLs\n\
         pub fn weapon_icon_data_url(game_id: &str, weapon_id: &str) -> Option<&'static str> {\n\
             match (game_id, weapon_id) {\n",
    );

    for (game, wid, rel) in weapons {
        embed_match_arm(&mut code, game, wid, rel, &root);
    }

    code.push_str("        _ => None,\n    }\n}\n\npub fn game_logo_data_url(game_id: &str) -> Option<&'static str> {\n    match game_id {\n");

    for (gid, rel) in logos {
        let path = root.join(rel);
        let bytes =
            fs::read(&path).unwrap_or_else(|e| panic!("read logo {}: {}", path.display(), e));
        let b64 = STANDARD.encode(&bytes);
        let data_url = format!("data:image/svg+xml;base64,{b64}");
        write!(
            &mut code,
            "        \"{gid}\" => Some(\"{}\"),\n",
            escape_data_url_for_rust_string(&data_url)
        )
        .unwrap();
        println!("cargo:rerun-if-changed={}", path.display());
    }

    code.push_str("        _ => None,\n    }\n}\n");

    fs::write(&out_path, code).unwrap();

    tauri_build::build();
}

fn embed_match_arm(code: &mut String, game: &str, wid: &str, rel: &str, root: &Path) {
    let path = root.join(rel);
    let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read icon {}: {}", path.display(), e));
    let mime = if rel.ends_with(".svg") {
        "image/svg+xml"
    } else {
        "image/png"
    };
    let b64 = STANDARD.encode(&bytes);
    let data_url = format!("data:{mime};base64,{b64}");
    write!(
        code,
        "        (\"{game}\", \"{wid}\") => Some(\"{}\"),\n",
        escape_data_url_for_rust_string(&data_url)
    )
    .unwrap();
    println!("cargo:rerun-if-changed={}", path.display());
}

fn escape_data_url_for_rust_string(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\\' => "\\\\".to_string(),
            '"' => "\\\"".to_string(),
            '\n' => "\\n".to_string(),
            '\r' => "\\r".to_string(),
            _ => c.to_string(),
        })
        .collect()
}
